### ISSUE TITLE
Install additional tesseract-ocr-* packages

### ISSUE THREAD

**Issue by chiefdeputy** [linuxserver/docker-paperless-ng#14]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
Analog to the official container, install additional OCR languages and add possibility to configure paperless to use them:
		tesseract-ocr-deu
		tesseract-ocr-fra
		tesseract-ocr-ita
		tesseract-ocr-spa
Env var used in official container: PAPERLESS_OCR_LANGUAGE

## Current Behavior
Only tesseract-ocr-eng is installed and supported.

## Alternatives Considered
Use official image which was not updated for a long time...

**Comment by chiefdeputy** [comment]
Sry, i was blind:
https://github.com/linuxserver/docker-paperless-ng/issues/10

Please close, or update documentation :)

**Comment by aptalca** [comment]
update what exactly?

**Comment by chiefdeputy** [comment]
Perhaps a small section in the readme which states that other ocr languages can be installed by a certain docker mod.
I think this would help. Thank you for your work!

**Comment by aptalca** [comment]
https://github.com/linuxserver/docker-paperless-ng#docker-mods
