### ISSUE TITLE
Consume method and volume

### ISSUE THREAD

**Issue by bisol84** [linuxserver/docker-paperless-ng#17]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
Possibility to have a separated consume volume (example on a nas) that can be accessed by the scanner.
As NFS doesn't work with ionotify, the polling by interval will be great
https://paperless-ng.readthedocs.io/en/latest/configuration.html#configuration-polling

## Current Behavior
The consume folder is hardcoded into the data folder and the method can't be changed

**Comment by j0nnymoe** [comment]
Defining `PAPERLESS_CONSUMPTION_DIR` in your compose will overwrite this.
