### ISSUE TITLE
Switch to paperless-ngx

### ISSUE THREAD

**Issue by eulores** [linuxserver/docker-paperless-ng#21]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

Consider using paperless-ngx instead of paperless-ng, as the core maintainer seems to be absent since September 2021.
https://github.com/paperless-ngx/paperless-ngx

## Current Behavior

A number of open issues and unresolved pull requests are now being addressed in the paperless-ngx fork.

**Comment by j0nnymoe** [comment]
Already in progress.
