### ISSUE TITLE
support for german, italian, spanish and french language

### ISSUE THREAD

**Issue by sukisoft** [linuxserver/docker-paperless-ng#4]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
Add the default languages paperless-ng is referring to in its own documentation. See [https://paperless-ng.readthedocs.io/en/latest/configuration.html#docker-specific-options](https://paperless-ng.readthedocs.io/en/latest/configuration.html#docker-specific-options) in the section _PAPERLESS_OCR_LANGUAGES_

Snipped from the doc:
_Additional OCR languages to install. By default, paperless comes with English, German, Italian, Spanish and French._

## Current Behavior
Sadly only english language is supported.

## Alternatives Considered
Alternatively, support the _PAPERLESS_OCR_LANGUAGES_ config to be respected, through which additional language packs can be installed.

**Comment by Roxedus** [comment]
You can use the [papermerge ocr](https://github.com/linuxserver/docker-mods/tree/papermerge-multilangocr) mod to install additional ocr packages.

**Comment by LeoKlaus** [comment]
Using the environment variables
`DOCKER_MODS=linuxserver/mods:papermerge-multilangocr` and
`PAPERLESS_OCR_LANGUAGE=deu`
Doesn't work, am I missing something?

**Comment by j0nnymoe** [comment]
@LeoKlaus once the mod is installed, you'll still need to setup the paperless config to use those.

**Comment by LeoKlaus** [comment]
> @LeoKlaus once the mod is installed, you'll still need to setup the paperless config to use those.

I think I should add that Paperless-ng does accept the environment variable and tries to change the OCR language, it just complains that the language wasn't installed.
`The selected ocr language deu is not installed. Paperless cannot OCR your documents without it. Please fix PAPERLESS_OCR_LANGUAGE.`

**Comment by tobbenb** [comment]
It isn't enough to just add the OCR mod, you also need to set the language with OCRLANG variable to install the correct language.

**Comment by LeoKlaus** [comment]
Oh, I See. So I did miss something.
Simply setting the environment variable OCRLANG to my three letter code would suffice?
Is this related to the docker-mods or paperless-ng?

**Comment by aptalca** [comment]
https://github.com/linuxserver/docker-mods/tree/papermerge-multilangocr#multi-language-ocr---docker-mod-for-papermerge

**Comment by LeoKlaus** [comment]
It does work now, thank you guys!
